name: build

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - master
      - develop
      - features/**
      - dependabot/**

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: ['8']
        os: [windows-latest]
    steps:
      - uses: actions/checkout@v1
      - name: Setup environment with node ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}
      - name: Install U1
        run: |
          npm install -g yarn
          yarn install
      - name: test
        run: |
          yarn run test:unit:coverage
      - name: build
        run: |
          yarn run build
