name: build

on:
  push:
    branches:
      - develop
      - master
      - feature/**
      - dependabot/**
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ['8']
        os: [windows-latest]
    steps:
      - uses: actions/checkout@v1
      - name: Setup environment with node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: |
          npm install -g yarn
          yarn install

      - name: test
      - run: |
          yarn run test:unit:coverage

      - name: build
      - run: |
          yarn run build:win
